package com.model;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class TAdmin implements java.io.Serializable {

	// Fields

	private Integer userId;

	private String userName;

    public TAdmin() {

    }

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public String getUserhmacmd5() {
		return userhmacmd5;
	}

	public void setUserhmacmd5(String userhmacmd5) {
		this.userhmacmd5 = userhmacmd5;
	}

	private String userPw;

	private String userhmacmd5;

	public TAdmin(Integer userId, String userName, String userPw, String userhmacmd5) {
		this.userId = userId;
		this.userName = userName;
		this.userPw = userPw;
		this.userhmacmd5 = userhmacmd5;
	}

}