package com.model;

import javax.persistence.Column;
import java.util.Date;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable
{

	// Fields

	public TUser(Integer userId, String userName, String userPw, String userhmacmd5, int userType, String userRealname, String userAddress, String userSex, String userTel, String userEmail, String userQq, String userMan, String userAge, String userBirthday, String userXueli, String userDel, String userOne1, String userOne2, String userOne3, String userOne4, String userOne5, Integer userOne6, Integer userOne7, Integer userOne8, Date userOne9, Date userOne10, Long userOne11, Long userOne12) {
		this.userId = userId;
		this.userName = userName;
		this.userPw = userPw;
		this.userhmacmd5 = userhmacmd5;
		this.userType = userType;
		this.userRealname = userRealname;
		this.userAddress = userAddress;
		this.userSex = userSex;
		this.userTel = userTel;
		this.userEmail = userEmail;
		this.userQq = userQq;
		this.userMan = userMan;
		this.userAge = userAge;
		this.userBirthday = userBirthday;
		this.userXueli = userXueli;
		this.userDel = userDel;
		this.userOne1 = userOne1;
		this.userOne2 = userOne2;
		this.userOne3 = userOne3;
		this.userOne4 = userOne4;
		this.userOne5 = userOne5;
		this.userOne6 = userOne6;
		this.userOne7 = userOne7;
		this.userOne8 = userOne8;
		this.userOne9 = userOne9;
		this.userOne10 = userOne10;
		this.userOne11 = userOne11;
		this.userOne12 = userOne12;
	}

	private Integer userId;

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public String getUserhmacmd5() {
		return userhmacmd5;
	}

	public void setUserhmacmd5(String userhmacmd5) {
		this.userhmacmd5 = userhmacmd5;
	}

	public int getUserType() {
		return userType;
	}

	public void setUserType(int userType) {
		this.userType = userType;
	}

	public String getUserRealname() {
		return userRealname;
	}

	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}

	public String getUserAddress() {
		return userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserSex() {
		return userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public String getUserTel() {
		return userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserQq() {
		return userQq;
	}

	public void setUserQq(String userQq) {
		this.userQq = userQq;
	}

	public String getUserMan() {
		return userMan;
	}

	public void setUserMan(String userMan) {
		this.userMan = userMan;
	}

	public String getUserAge() {
		return userAge;
	}

	public void setUserAge(String userAge) {
		this.userAge = userAge;
	}

	public String getUserBirthday() {
		return userBirthday;
	}

	public void setUserBirthday(String userBirthday) {
		this.userBirthday = userBirthday;
	}

	public String getUserXueli() {
		return userXueli;
	}

	public void setUserXueli(String userXueli) {
		this.userXueli = userXueli;
	}

	public String getUserDel() {
		return userDel;
	}

	public void setUserDel(String userDel) {
		this.userDel = userDel;
	}

	public String getUserOne1() {
		return userOne1;
	}

	public void setUserOne1(String userOne1) {
		this.userOne1 = userOne1;
	}

	public String getUserOne2() {
		return userOne2;
	}

	public void setUserOne2(String userOne2) {
		this.userOne2 = userOne2;
	}

	public String getUserOne3() {
		return userOne3;
	}

	public void setUserOne3(String userOne3) {
		this.userOne3 = userOne3;
	}

	public String getUserOne4() {
		return userOne4;
	}

	public void setUserOne4(String userOne4) {
		this.userOne4 = userOne4;
	}

	public String getUserOne5() {
		return userOne5;
	}

	public void setUserOne5(String userOne5) {
		this.userOne5 = userOne5;
	}

	public Integer getUserOne6() {
		return userOne6;
	}

	public void setUserOne6(Integer userOne6) {
		this.userOne6 = userOne6;
	}

	public Integer getUserOne7() {
		return userOne7;
	}

	public void setUserOne7(Integer userOne7) {
		this.userOne7 = userOne7;
	}

	public Integer getUserOne8() {
		return userOne8;
	}

	public void setUserOne8(Integer userOne8) {
		this.userOne8 = userOne8;
	}

	public Date getUserOne9() {
		return userOne9;
	}

	public void setUserOne9(Date userOne9) {
		this.userOne9 = userOne9;
	}

	public Date getUserOne10() {
		return userOne10;
	}

	public void setUserOne10(Date userOne10) {
		this.userOne10 = userOne10;
	}

	public Long getUserOne11() {
		return userOne11;
	}

	public void setUserOne11(Long userOne11) {
		this.userOne11 = userOne11;
	}

	public Long getUserOne12() {
		return userOne12;
	}

	public void setUserOne12(Long userOne12) {
		this.userOne12 = userOne12;
	}

	private String userName;

	private String userPw;

	private String userhmacmd5;

	private int userType;

	private String userRealname;

	private String userAddress;

	private String userSex;

	private String userTel;

	private String userEmail;

	private String userQq;

	private String userMan;

	private String userAge;

	private String userBirthday;

	private String userXueli;
	
	private String userDel;
	
	private String userOne1;

	private String userOne2;

	private String userOne3;

	private String userOne4;

	private String userOne5;

	private Integer userOne6;

	private Integer userOne7;

	private Integer userOne8;

	private Date userOne9;

	private Date userOne10;

	private Long userOne11;

	private Long userOne12;

	// Constructors

	/** default constructor */
	public TUser()
	{
	}



}